const providers = [
  { id: "att-fiber", name: "AT&T Fiber", technology: ["fiber"], services: ["internet", "voice", "business"], strengths: ["symmetrical speeds on fiber plans", "low-latency fiber access", "broad multi-state footprint"], cautions: ["availability and offers vary by address", "mobile service is handled through separate wireless products"], bestFor: ["remote work", "gaming", "high upload use", "large households"] },
  { id: "frontier-fiber", name: "Frontier Fiber", technology: ["fiber"], services: ["internet", "voice", "business"], strengths: ["symmetrical fiber speeds", "strong fit for work-from-home and gaming", "multi-gig availability in some markets"], cautions: ["service quality and product availability vary by local market", "pricing must be verified for the address"], bestFor: ["remote work", "gaming", "streaming households"] },
  { id: "spectrum", name: "Spectrum", technology: ["cable", "fiber in select business areas"], services: ["internet", "mobile", "voice", "tv", "business"], strengths: ["wide cable footprint", "mobile and TV bundle options", "strong download-speed availability"], cautions: ["residential upload speeds may be lower than fiber", "local congestion and plant condition can affect experience"], bestFor: ["broad availability", "bundles", "streaming"] },
  { id: "verizon-fios", name: "Verizon Fios", technology: ["fiber"], services: ["internet", "mobile", "voice", "tv", "business"], strengths: ["symmetrical fiber speeds", "low latency", "wireless bundle opportunities"], cautions: ["limited geographic footprint", "offers vary by address"], bestFor: ["gaming", "remote work", "mobile bundles"] },
  { id: "quantum-fiber", name: "Quantum Fiber", technology: ["fiber"], services: ["internet", "business"], strengths: ["fiber-based symmetrical service", "simple internet-focused positioning"], cautions: ["market coverage varies", "equipment and pricing require address verification"], bestFor: ["remote work", "streaming", "high upload use"] },
  { id: "google-fiber", name: "Google Fiber", technology: ["fiber"], services: ["internet", "business"], strengths: ["high-capacity fiber", "symmetrical speeds", "straightforward product experience"], cautions: ["available only in selected cities", "installation timing varies by neighborhood"], bestFor: ["power users", "gaming", "large households"] },
  { id: "altafiber", name: "altafiber", technology: ["fiber", "copper in legacy areas"], services: ["internet", "voice", "tv", "business"], strengths: ["regional fiber expansion", "local-market support", "bundle options"], cautions: ["technology varies by address", "legacy areas may not receive fiber performance"], bestFor: ["regional customers", "bundles", "remote work on fiber"] },
  { id: "lumos", name: "Lumos", technology: ["fiber"], services: ["internet", "voice", "business"], strengths: ["fiber-to-the-home architecture", "symmetrical service design", "growing regional footprint"], cautions: ["availability is limited to built markets", "plans and install dates require address validation"], bestFor: ["remote work", "gaming", "fiber-first households"] },
  { id: "epb-fiber", name: "EPB Fiber Optics", technology: ["fiber"], services: ["internet", "voice", "tv", "business"], strengths: ["municipal fiber network", "symmetrical high-speed service", "local operations"], cautions: ["restricted to the local service territory"], bestFor: ["Chattanooga-area households", "remote work", "business"] },
  { id: "metronet", name: "Metronet", technology: ["fiber"], services: ["internet", "voice", "business"], strengths: ["fiber-to-the-premises", "regional expansion", "symmetrical-speed positioning"], cautions: ["fees and plan details require verification", "availability varies by neighborhood"], bestFor: ["remote work", "gaming", "families"] },
  { id: "ziply-fiber", name: "Ziply Fiber", technology: ["fiber", "dsl in legacy areas"], services: ["internet", "voice", "business"], strengths: ["fiber multi-gig options in parts of the Northwest", "strong upload performance on fiber"], cautions: ["technology differs by address", "legacy DSL areas should not be represented as fiber"], bestFor: ["Northwest fiber customers", "creators", "gaming"] },
  { id: "brightspeed-fiber", name: "Brightspeed Fiber", technology: ["fiber", "dsl in legacy areas"], services: ["internet", "voice", "business"], strengths: ["fiber expansion in underserved markets", "symmetrical service where fiber is available"], cautions: ["legacy copper remains in some areas", "address-level technology verification is essential"], bestFor: ["new fiber markets", "remote work", "streaming"] },
];

const articles = [
  { id: "fiber-vs-cable", type: "technology", title: "Fiber versus cable", tags: ["fiber", "cable", "latency", "upload"], content: { summary: "Fiber commonly offers symmetrical upload and download performance and low latency. Cable commonly offers broad availability and strong download speeds, while upload capacity may be lower.", guidance: ["Do not claim a provider is more reliable without local evidence.", "Match technology to the customer's actual needs."] } },
  { id: "wifi-coverage", type: "wifi", title: "Wi-Fi coverage", tags: ["wifi", "mesh", "coverage", "dead zones"], content: { summary: "Internet speed and in-home Wi-Fi coverage are different problems. Router placement, construction materials, floor count, interference, and device density affect coverage.", guidance: ["Ask about square footage, floors, router location, and dead zones.", "Recommend mesh only when coverage needs justify it."] } },
  { id: "gaming-needs", type: "technology", title: "Gaming requirements", tags: ["gaming", "latency", "jitter", "packet loss"], content: { summary: "Gaming quality depends more on latency, jitter, packet loss, and stable Wi-Fi or Ethernet than on extreme download speed.", guidance: ["Avoid overselling multi-gig service solely for gaming.", "Prioritize stable wired or strong Wi-Fi connectivity."] } },
  { id: "remote-work", type: "customer-fit", title: "Remote work requirements", tags: ["remote work", "video calls", "upload", "reliability"], content: { summary: "Remote workers benefit from stable service, adequate upload capacity, low packet loss, backup planning, and strong coverage where they work.", guidance: ["Ask about video meetings, VPN use, file uploads, and business-critical downtime."] } },
  { id: "ethical-sales", type: "sales", title: "Ethical broadband sales", tags: ["sales", "ethics", "disclosure"], content: { summary: "Recommendations must distinguish verified facts, estimates, and unknowns. Do not invent prices, installation dates, reliability claims, or eligibility.", guidance: ["Disclose uncertainty.", "Confirm offers at the service address.", "Recommend based on customer fit before commission economics."] } },
  { id: "discovery-framework", type: "sales", title: "ConnectIQ discovery framework", tags: ["sales", "discovery", "qualification"], content: { summary: "Discover the current provider, monthly bill, pain points, household usage, work-from-home needs, gaming, streaming, mobile interest, installation timing, and budget before closing.", guidance: ["Ask one focused question at a time.", "Reflect the customer's stated problem before recommending."] } },
  { id: "price-objection", type: "objection", title: "Price objection", tags: ["price", "budget", "objection", "savings"], content: { summary: "A price objection may reflect total monthly cost, fear of hidden fees, low perceived value, or switching risk.", guidance: ["Clarify the current all-in bill.", "Compare value and tradeoffs, not headline price alone.", "Never promise savings without verified plan pricing."] } },
  { id: "switching-objection", type: "objection", title: "Fear of switching", tags: ["switching", "installation", "downtime", "objection"], content: { summary: "Customers may fear downtime, installation problems, equipment changes, email loss, or phone-number portability issues.", guidance: ["Explain the transition process.", "Do not cancel existing service before the new service is working.", "Treat porting as subject to eligibility verification."] } },
  { id: "mobile-bundles", type: "mobile", title: "Mobile bundle guidance", tags: ["mobile", "bundle", "wireless"], content: { summary: "Some internet providers offer mobile service or bundle discounts, but eligibility, network terms, device financing, and promotional pricing vary.", guidance: ["Verify mobile availability and terms.", "Compare total household cost and coverage, not discount alone."] } },
  { id: "installation-guidance", type: "installation", title: "Installation expectations", tags: ["installation", "appointment", "self-install"], content: { summary: "Installation may be professional or self-install depending on provider, technology, address readiness, and equipment.", guidance: ["Never guarantee an appointment date before provider confirmation.", "Ask about move-in date and service continuity."] } },
];

export function getSeedCatalog() {
  return { providers: structuredClone(providers), articles: structuredClone(articles) };
}
