function money(v){return Number.isFinite(Number(v))?`$${Number(v).toFixed(0)}`:"";}
function names(f){const k=[];if(f.currentProvider)k.push(`you currently use ${f.currentProvider}`);if(f.monthlyBill)k.push(`you pay about ${money(f.monthlyBill)} per month`);return k.length?`I understand that ${k.join(" and ")}. `:"";}
export function buildAdvisorResponse({routerResult={},providers=[],quote=null}={}){const m=routerResult.memory||{},f=m.facts||{},p=m.painPoints||[],n=m.householdNeeds||[],pref=m.preferences||{},c=routerResult.conversation||{},primary=routerResult.intent?.primary||"discovery",provider=providers[0]||null;
 if(c.analysis?.humanHandoff)return{message:"I can connect you with a sales advisor. Before I do, I’ll preserve everything you have already shared so you do not need to repeat it.",suggestedReplies:["Call me","Continue here"]};
 if(primary==="objection")return{message:"That is a fair concern. I’ll compare total monthly cost, reliability, speed, equipment, and any known tradeoffs before asking you to choose.",suggestedReplies:["Show best value","Compare reliability","What will it cost?"]};
 if(provider&&(primary==="recommendation"||routerResult.toolsInvoked?.includes("recommendation"))){const reason=p.includes("reliability")||n.includes("workFromHome")?"its connection type and performance profile align with reliable work and video calls":pref.primaryPriority==="price"?"it appears to offer the strongest price-to-performance fit":"it provides the strongest overall fit from the available options";return{message:`${provider.displayName||provider.name||"This provider"} is currently my leading recommendation because ${reason}.`,suggestedReplies:["Why is it best?","Show alternatives","Build my quote"]};}
 const ack=names(f);const priorityKnown=Boolean(pref.primaryPriority||p.length||n.length);let next,key;
 if(!f.currentProvider){next="Who is your current internet provider?";key="currentProvider";}
 else if(!f.monthlyBill){next="About how much do you pay each month?";key="monthlyBill";}
 else if(!priorityKnown){next="What matters most to you: a lower price, better reliability, faster speed, or stronger Wi-Fi coverage?";key="priority";}
 else if(!providers.length){next="I have enough information to start. Enter your service address so I can check which providers are actually available.";key="address";}
 else{next="I have enough information to compare your available options. Would you like my best recommendation or a side-by-side comparison?";key="recommendation";}
 return{message:`${ack}${next}`,questionKey:key,activeThread:c.activeThread||"discovery",suggestedReplies:key==="priority"?["Lowest price","Best reliability","Fastest speed","Better Wi-Fi"]:key==="recommendation"?["Best recommendation","Compare options"]:[]};}
export function buildAdvisorQuote({routerResult={},providers=[],selectedProvider=null}={}){const f=routerResult.memory?.facts||{},provider=selectedProvider||providers[0]||null,monthly=Number(provider?.price||provider?.monthlyPrice||provider?.estimatedMonthlyPrice||0)||null,current=Number(f.monthlyBill||0)||null;return{provider:provider?.displayName||provider?.brand_name||provider?.name||null,technology:provider?.technology||provider?.technologyType||provider?.technology_code_type||null,downloadMbps:Number(provider?.maxDownload||provider?.maxdown||provider?.downloadSpeed||0)||null,uploadMbps:Number(provider?.maxUpload||provider?.maxup||provider?.uploadSpeed||0)||null,estimatedMonthlyPrice:monthly,estimatedMonthlySavings:monthly&&current?Math.max(0,current-monthly):null,status:provider?"ESTIMATE_READY":"NEEDS_PROVIDER",disclaimer:"Pricing, availability, taxes, equipment, and installation details must be confirmed before submission."};}
