import { analyzeIntent } from "./intentAnalyzer.js";
import { learnFromMessage, getCustomerMemory } from "./customerMemoryService.js";
import { orchestrateConversation } from "./conversationOrchestrator.js";
import { listTools, toolRegistryHealth } from "./toolRegistry.js";
import { executeTools } from "./executionPipeline.js";
import { recordDecision, recordTurn, getDiagnostics, telemetryHealth } from "./telemetryService.js";
import { registerDefaultTools } from "./defaultTools.js";
let initialized=false;
export function initializeToolRouter(){if(!initialized){registerDefaultTools();initialized=true;}return routerHealth();}
function selectTools(intent){const selected=[];for(const tool of listTools({enabledOnly:true})){if(tool.intents.some(item=>intent.intents.some(match=>match.intent===item)))selected.push(tool.name);}if(!selected.includes("leadQualification"))selected.push("leadQualification");return selected;}
function composeResponse(intent,pipeline,memory,conversation){const ok=pipeline.executions.filter(i=>i.success);const lead=ok.find(i=>i.tool==="leadQualification")?.data;const order=ok.find(i=>i.tool==="orderReadiness")?.data;return{message:ok.flatMap(i=>i.messages||[]).filter(Boolean).join(" "),nextAction:conversation.analysis.humanHandoff?"human_handoff":order?.ready?"continue_to_order":intent.primary==="recommendation"?"present_recommendation":"continue_discovery",leadScore:lead?.score??null,orderReady:Boolean(order?.ready),knownFacts:memory.facts,activeThread:conversation.activeThread,openThreads:Object.values(conversation.threads||{}).filter(t=>t.status==="open").map(t=>t.topic)};}
export async function routeConversationTurn({sessionId,message,stage="DISCOVERY",context={}}){initializeToolRouter();if(!sessionId)throw new Error("sessionId is required.");if(!String(message||"").trim())throw new Error("message is required.");const startedAt=Date.now();const learned=learnFromMessage(sessionId,message);const memory=getCustomerMemory(sessionId);const intent=analyzeIntent(message,{...context,stage,memory});const conversation=orchestrateConversation({sessionId,message,memory,intent});const toolNames=selectTools(intent);recordDecision({sessionId,stage,primaryIntent:intent.primary,intents:intent.intents,tools:toolNames,reason:`Selected tools for ${intent.intents.map(i=>i.intent).join(", ")} with active thread ${conversation.activeThread}.`,confidence:intent.intents[0]?.confidence||0});const pipeline=await executeTools(toolNames,{sessionId,message,stage,context,intent,learned,memory,conversation});const response=composeResponse(intent,pipeline,memory,conversation);const turn={ok:pipeline.success,sessionId,stage,intent,conversation,toolsInvoked:toolNames,pipeline,memory,response,durationMs:Date.now()-startedAt};recordTurn(turn);return turn;}
export function routerDiagnostics(options={}){return getDiagnostics(options);}
export function routerHealth(){return{ok:true,service:"connectiq-conversation-intelligence",version:"0.8.0",registry:toolRegistryHealth(),telemetry:telemetryHealth()};}
