import test from "node:test";
import assert from "node:assert/strict";
import { routeConversationTurn } from "../services/toolRouter/routerService.js";
import { clearCustomerMemory } from "../services/toolRouter/customerMemoryService.js";
import { clearConversationOrchestrator } from "../services/toolRouter/conversationOrchestrator.js";
import { buildAdvisorResponse } from "../services/aiAdvisor/responseBuilder.js";

test.beforeEach(()=>{clearCustomerMemory();clearConversationOrchestrator();});
test("extracts multiple facts and needs from one natural message",async()=>{const r=await routeConversationTurn({sessionId:"ci-1",message:"I have Spectrum, pay $135 a month, work from home and Wi-Fi upstairs is terrible."});assert.equal(r.memory.facts.currentProvider,"Spectrum");assert.equal(r.memory.facts.monthlyBill,135);assert.ok(r.memory.householdNeeds.includes("workFromHome"));assert.ok(r.memory.painPoints.includes("wifiCoverage"));assert.ok(r.conversation.openThreads.includes("pricing"));});
test("standalone provider and natural monthly amount are understood",async()=>{await routeConversationTurn({sessionId:"ci-2",message:"AT&T"});const r=await routeConversationTurn({sessionId:"ci-2",message:"115 a month and I need a cheaper price"});assert.equal(r.memory.facts.currentProvider,"AT&T");assert.equal(r.memory.facts.monthlyBill,115);assert.equal(r.memory.preferences.primaryPriority,undefined);assert.ok(r.memory.painPoints.includes("price"));});
test("short priority answer advances discovery",async()=>{await routeConversationTurn({sessionId:"ci-3",message:"I have AT&T and pay $115 monthly"});const r=await routeConversationTurn({sessionId:"ci-3",message:"price"});assert.equal(r.memory.preferences.primaryPriority,"price");const a=buildAdvisorResponse({routerResult:r});assert.doesNotMatch(a.message,/What matters most/i);assert.match(a.message,/service address|enough information/i);});
test("tracks side topics without losing the primary goal",async()=>{const r=await routeConversationTurn({sessionId:"ci-4",message:"Spectrum keeps going out. Do you offer mobile? I work from home and need this fixed before Friday."});assert.ok(r.conversation.openThreads.includes("reliability"));assert.ok(r.conversation.openThreads.includes("mobile"));assert.equal(r.conversation.analysis.urgency,"high");assert.equal(r.conversation.primaryGoal,"internet_recommendation");});
test("recognizes corrections and human handoff",async()=>{const first=await routeConversationTurn({sessionId:"ci-5",message:"I have Spectrum"});assert.equal(first.memory.facts.currentProvider,"Spectrum");const second=await routeConversationTurn({sessionId:"ci-5",message:"Actually I have Xfinity and I want to talk to a person"});assert.equal(second.memory.facts.currentProvider,"Xfinity");assert.equal(second.conversation.analysis.correction,true);assert.equal(second.response.nextAction,"human_handoff");});
