import { CONVERSATION_STATES } from "../conversationState";

const transitions = {
  [CONVERSATION_STATES.GREETING]: [CONVERSATION_STATES.ADDRESS],
  [CONVERSATION_STATES.ADDRESS]: [CONVERSATION_STATES.LOOKUP],
  [CONVERSATION_STATES.LOOKUP]: [CONVERSATION_STATES.DISCOVERY, CONVERSATION_STATES.ERROR],
  [CONVERSATION_STATES.DISCOVERY]: [CONVERSATION_STATES.RECOMMENDATION],
  [CONVERSATION_STATES.RECOMMENDATION]: [CONVERSATION_STATES.COMPARE, CONVERSATION_STATES.QUOTE],
  [CONVERSATION_STATES.COMPARE]: [CONVERSATION_STATES.QUOTE],
  [CONVERSATION_STATES.QUOTE]: [CONVERSATION_STATES.CUSTOMER_INFO],
  [CONVERSATION_STATES.CUSTOMER_INFO]: [CONVERSATION_STATES.READY],
  [CONVERSATION_STATES.READY]: [CONVERSATION_STATES.COMPLETE],
  [CONVERSATION_STATES.ERROR]: [CONVERSATION_STATES.ADDRESS],
};

export function canTransition(from, to) {
  return Boolean(transitions[from]?.includes(to));
}

export function transitionSession(session, to, patch = {}) {
  if (session.step !== to && !canTransition(session.step, to)) {
    return { ...session, ...patch, step: to };
  }
  return { ...session, ...patch, step: to };
}
